// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2HdcmyXQje-xEnmICnUOXsuRRxyo0hSQ',
    appId: '1:664763746918:web:e44178272ecd8121843ba7',
    messagingSenderId: '664763746918',
    projectId: 'campusconnect-a6244',
    authDomain: 'campusconnect-a6244.firebaseapp.com',
    storageBucket: 'campusconnect-a6244.firebasestorage.app',
    measurementId: 'G-PEFRCWW8E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaptskWpvXnOwOGN7GHFviq16jdqI5U80',
    appId: '1:664763746918:android:ad9807506a62e3f2843ba7',
    messagingSenderId: '664763746918',
    projectId: 'campusconnect-a6244',
    storageBucket: 'campusconnect-a6244.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4klcNJ0Pn3qj0EGcxdtEQpnoNO05VTbY',
    appId: '1:664763746918:ios:435986e22379effe843ba7',
    messagingSenderId: '664763746918',
    projectId: 'campusconnect-a6244',
    storageBucket: 'campusconnect-a6244.firebasestorage.app',
    iosBundleId: 'com.example.campusconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4klcNJ0Pn3qj0EGcxdtEQpnoNO05VTbY',
    appId: '1:664763746918:ios:435986e22379effe843ba7',
    messagingSenderId: '664763746918',
    projectId: 'campusconnect-a6244',
    storageBucket: 'campusconnect-a6244.firebasestorage.app',
    iosBundleId: 'com.example.campusconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2HdcmyXQje-xEnmICnUOXsuRRxyo0hSQ',
    appId: '1:664763746918:web:5795f57a5c7fb018843ba7',
    messagingSenderId: '664763746918',
    projectId: 'campusconnect-a6244',
    authDomain: 'campusconnect-a6244.firebaseapp.com',
    storageBucket: 'campusconnect-a6244.firebasestorage.app',
    measurementId: 'G-285EHNQF7B',
  );
}
